### ISSUE TITLE
convert fetch requests to useSWR hook

### ISSUE THREAD

**Issue by altude** [huelet/frontend#4]

**Comment by lerichardson** [comment]
this is quite the easy thing to fix if anyone's interested in making a first pull request, check the [docs here](https://swr.vercel.app/).

in other words I don't want to have to do this myself

**Comment by harishfalco** [comment]
Greetings, @lerichardson  Since I'm new to contributing to open-source, I'd want to fix this problem. Give it to me, if possible.

**Comment by lerichardson** [comment]
> Greetings, @lerichardson  Since I'm new to contributing to open-source, I'd want to fix this problem. Give it to me, if possible.

absolutely! make a pr whenever you're ready!

**Comment by lerichardson** [comment]
@harishfalco whenever you're ready, just run this code in your console, and you're ready to start coding:
```sh
git clone https://github.com/huelet/frontend.git
cd frontend
git checkout convert-fetch-requests-to-useswr
yarn
```

please make sure you have `node.js` ([install guide here](https://github.com/nvm-sh/nvm)) and `yarn` (`npm i -g yarn`) before running all of this. if you encounter any issues, feel free to reply!

**Comment by itslevir** [comment]
Stale issue
